# Generated by Django 2.2.2 on 2019-06-20 05:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Author Name', max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='birth')),
                ('book_number', models.IntegerField(help_text='Book number', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Book Name', max_length=100, null=True)),
                ('book_author', models.CharField(help_text='Book author', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='unique id', primary_key=True, serialize=False)),
                ('book_name', models.CharField(help_text='Book Name', max_length=100, null=True)),
                ('timestamp', models.DateField(auto_now=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('author_name', models.ForeignKey(help_text='book author', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.author')),
            ],
        ),
    ]
